using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Singleton<T> : MonoBehaviour where T : Component
{
    /// <summary>
    /// РЬЙЬ СОЗсУГИЎПЁ ЧпДТСі ШЎРЮЧЯДТ КЏМі
    /// </summary>
    private static bool isShutDown = false;

    /// <summary>
    /// НЬБлХцРЧ АДУМ
    /// </summary>
    private static T instance;

    /// <summary>
    /// НЬБлХцРЧ АДУМИІ РаБт РЇЧб ЧСЗЮЦлЦМ
    /// </summary>
    public static T Instance
    {
        get
        {
            // РЬЙЬ СОЗс УГИЎ ЧпРЛ ЖЇ
            if(isShutDown)
            {
                // АцАэ УтЗТ
                Debug.LogWarning($"{typeof(T).Name} НЬБлХцРК РЬЙЬ ЛшСІСпРЬДй.");
                return null;
            }
            if(instance == null)
            {
                if(FindObjectOfType<T>(true) == null)
                {
                    GameObject obj = new GameObject();  // ПРКъСЇЦЎ Л§МК
                    obj.name = $"{typeof(T).Name} Singleton";   // РЬИЇ УпАЁ
                    instance = obj.AddComponent<T>();   // НЬБлХц АДУМ УпАЁ
                    DontDestroyOnLoad(instance.gameObject); // ОРРЬ ЛчЖѓСњ ЖЇ GameObjectАЁ ЛшСІЕЧСі ОЪЕЕЗЯ ЧЯДТ ЧдМі
                }
                else
                {
                    Debug.Log($"FindObjectOfType<T>(true) = {FindObjectOfType<T>(true)} АЁВћ ПЉБтЗЮ КќСіДТАЭЕщРЬ РжДй.");
                    Debug.Log("ПЉБтЗЮ КќСіИщ РЯДм КёШАМКШ­ЕШ ПРКъСЇЦЎПЁ НЬБлХцРЛ УпАЁЧЯСі ОЪОвГЊ ШЎРЮ");
                }
            }
            return instance;
        }
    }

    /// <summary>
    /// ЧиДч ФФЦїГЭЦЎАЁ ЛчПыЕЧДТ УЙОРПЁМ­ ЧбЙј AwakeАЁ ЙпЕПЕШДй.
    /// </summary>
    protected virtual void Awake()
    {
        if(instance == null) // ОРПЁ ЙшФЁЕЧОюРжДТ УЙЙјТА НЬБлХц GameObject
        {
            instance = this as T;

            DontDestroyOnLoad(instance.gameObject); // ОРРЬ ЛчЖѓСњ ЖЇ GameObjectАЁ ЛшСІЕЧСі ОЪЕЕЗЯ ЧЯДТ ЧдМі
        }
        else // УЙЙјТА НЬБлХц АдРг ПРКъСЇЦЎАЁ ИИЕщОюСј РЬШФПЁ ИИЕщОюСј НЬБлХц GameObject
        {
            if(instance != this) // ААРК АДУМРЯМіЕЕ РжОюМ­ ОЦДвАцПьИИ УГИЎ
            {
                Destroy(this.gameObject);   // УЙЙјТА НЬБлХцАњ ДйИЅ АДУМИщ ЛшСІ
            }
        }
    }

    protected virtual void OnEnable()
    {
        SceneManager.sceneLoaded += OnSceneLoaded;
    }

    protected virtual void OnDisable()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
    }

    /// <summary>
    /// ЧСЗЮБзЗЅРЬ СОЗсЕЧОњРЛ ЖЇ НЧЧрЕЧДТ ЧдМі
    /// </summary>
    private void OnApplicationQuit()
    {
        isShutDown = true;
    }

    protected virtual void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        Init(scene, mode);
    }

    protected virtual void Init(Scene scene, LoadSceneMode mode)
    {

    }
}
