using Cinemachine;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.InputSystem;

public class Player_Controller : MonoBehaviour
{
    PlayerInputAction inputAction;
    public PlayerInputAction InputAction => inputAction;
    CharacterController controller;
    public CharacterController Controller => controller;
    CinemachineVirtualCamera cinemachine;
    public CinemachineVirtualCamera Cinemachine => cinemachine;

    public Transform cameraRoot;    // ФЋИоЖѓ РЇФЁ
    Vector3 moveDir = Vector3.zero; // РЇФЁКЏМі

    float currentSpeed = 0.0f;  // ЧіРч РЬЕПМгЕЕ
    float walkSpeed = 3.0f;     // АШБт МгЕЕ
    float sprintSpeed = 4.7f;   // ДоИЎБт МгЕЕ
    bool sprintCheck = false;   // ДоИЎБт УМХЉ

    float jumpHeight = 4.0f;        // СЁЧС ГєРЬ
    bool jumpCheck = false;         // СЁЧС УМХЉ
    float jumpCheckHeight = 0.0f;   // СЁЧС ГєРЬ ШЎРЮ
    float gravity = 9.8f;           // СпЗТ ХЉБт
    int jumpCount = 0;              // СЁЧС ШНМі - ДѕКэСЁЧС БнСі

    float crouchDecrease = 1.0f;    // ПѕХЉИЎБт РЬЕПМгЕЕ АЈМвЗЎ
    bool crouchCheck = false;       // ПѕХЉИЎБт УМХЉ

    float rotateSensitiveX = 7.5f;  // Ш­Ищ xЙцЧт РќШЏ ЙЮАЈЕЕ
    float rotateSensitiveY = 10.0f; // Ш­Ищ yЙцЧт РќШЏ ЙЮАЈЕЕ
    float curRotateY = 0.0f;        // ЧіРч РЬЕПЧб yЙцЧт

    Vector3 boxsize = new Vector3(0.25f, 0.125f, 0.25f);
    Vector3 groundCheckPos; // ЙйДк РЇФЁ

    public Action onSprinting;
    public Action offSprinting;

    bool isMove = false;
    public bool isStamina = false;

    private void Start()
    {
        currentSpeed = walkSpeed;
    }

    private void Awake()
    {
        inputAction = new PlayerInputAction();
        controller = GetComponent<CharacterController>();
        cinemachine = GetComponentInChildren<CinemachineVirtualCamera>();

        cameraRoot = transform.GetChild(0);
    }

    private void OnEnable()
    {
        inputAction.Player.Enable();
        inputAction.Player.Move.performed += OnMove;
        inputAction.Player.Move.canceled += OnMove;
        inputAction.Player.Sprint.performed += OnSprint;
        inputAction.Player.Sprint.canceled += OnSprint;
        inputAction.Player.Jump.performed += OnJump;
        inputAction.Player.Crouch.performed += OnCrouch;
        inputAction.Player.Crouch.canceled += OnCrouch;

        inputAction.Mouse.Enable();
        inputAction.Mouse.MouseVector2.performed += OnMouseDelta;
        inputAction.Mouse.MouseLeftClick.performed += OnMouseLeftClick;
        inputAction.Mouse.MouseRightClick.performed += OnMOuseRightClick;
    }

    private void OnDisable()
    {

        inputAction.Mouse.MouseRightClick.performed -= OnMOuseRightClick;
        inputAction.Mouse.MouseLeftClick.performed -= OnMouseLeftClick;
        inputAction.Mouse.MouseVector2.performed -= OnMouseDelta;
        inputAction.Mouse.Enable();

        inputAction.Player.Crouch.canceled -= OnCrouch;
        inputAction.Player.Crouch.performed -= OnCrouch;
        inputAction.Player.Jump.performed -= OnJump;
        inputAction.Player.Sprint.canceled -= OnSprint;
        inputAction.Player.Sprint.performed -= OnSprint;
        inputAction.Player.Move.canceled -= OnMove;
        inputAction.Player.Move.performed -= OnMove;
        inputAction.Player.Enable();
    }

    private void Update()
    {
        if(!IsGrounded())
            moveDir.y -= gravity * Time.deltaTime;

        if (isMove && sprintCheck)
        {
            isStamina = false;
            onSprinting?.Invoke();
        }

        // ЧУЗЙРЬОю x, zСТЧЅ РЬЕП
        controller.Move(Time.deltaTime * (currentSpeed * crouchDecrease) * transform.TransformDirection(new Vector3(moveDir.x, 0.0f, moveDir.z)));
        // ЧУЗЙРЬОю yСТЧЅ РЬЕП
        controller.Move(Time.deltaTime * new Vector3(0.0f, moveDir.y, 0.0f));
    }

    private void OnMove(InputAction.CallbackContext context)
    {
        Vector2 dir = context.ReadValue<Vector2>();
        moveDir.x = dir.x; moveDir.z = dir.y;

        if (context.performed)
        {
            isMove = true;

        }
        else
        {
            isMove = false;
            OffSprinting();
        }
    }

    private void OnSprint(InputAction.CallbackContext context)
    {
        if(!crouchCheck)    // ПѕХЉИЎБт ЛѓХТАЁ ОЦДв ЖЇ
        {
            if (context.performed)
            {
                sprintCheck = true;
                currentSpeed = sprintSpeed;
            }
            else
            {
                if (sprintCheck)
                {
                    OffSprinting();
                }
            }
        }
    }

    private void OnJump(InputAction.CallbackContext context)
    {
        if(!crouchCheck  && IsGrounded())
        {
            if(jumpCount < 1)   // ДѕКэСЁЧС ИЗБт
            {
                moveDir.y = jumpHeight;
            
                if(jumpCount == 0)
                {
                    jumpCheckHeight = transform.position.y + controller.radius * 0.3f;
                }
                jumpCheck = true;
                jumpCount++;
            }
        }
    }

    private void OnCrouch(InputAction.CallbackContext context)
    {
        if (!sprintCheck && IsGrounded())
        {
            if (context.performed)
            {
                crouchDecrease = 0.5f;  // АЈМвЗЎ 0.5Йш
                crouchCheck = true;

                cameraRoot.transform.position += new Vector3(0.0f, -0.5f, 0.0f);
            }
            else
            {
                crouchDecrease = 1.0f;  // АЈМвЗЎ ОјРН
                crouchCheck = false;
                
                cameraRoot.transform.position += new Vector3(0.0f, 0.5f, 0.0f);
            }
        }
    }

    private void OnMouseDelta(InputAction.CallbackContext context)
    {
        Vector2 temp = context.ReadValue<Vector2>();

        // РдЗТЙоРК СТЧЅИІ xЙцЧт РќШЏ ЙЮАЈЕЕИИХ­ РЬЕП
        float rotateX = temp.x * rotateSensitiveX * Time.fixedDeltaTime;
        transform.Rotate(Vector3.up, rotateX);
        float rotateY = temp.y * rotateSensitiveY * Time.fixedDeltaTime;
        curRotateY -= rotateY;

        // yЙцЧт РќШЏРЧ УжМв Йз УжДыЗЎРЛ СіСЄ
        curRotateY = Mathf.Clamp(curRotateY, -60.0f, 60.0f);

        cameraRoot.rotation = Quaternion.Euler(curRotateY, cameraRoot.eulerAngles.y, cameraRoot.eulerAngles.z);
    }

    private void OnMouseLeftClick(InputAction.CallbackContext context)
    {

    }

    private void OnMOuseRightClick(InputAction.CallbackContext context)
    {

    }

    public void OffSprinting()
    {
        sprintCheck = false;
        currentSpeed = walkSpeed;

        offSprinting?.Invoke();
    }

    private bool IsGrounded()
    {
        // СЁЧС СпРЯ ЖЇ, ЧіРч yГєРЬАЁ ИёЧЅ yКИДй ГєРИИщ
        if(jumpCheck && transform.position.y > jumpCheckHeight)
        {
            jumpCheck = false;
        }

        // ФГИЏХЭ ЙиРИЗЮ ЙйДкРЛ УМХЉЧЯДТ ЙкНКИІ Л§МК
        groundCheckPos = new Vector3(transform.position.x, transform.position.y + controller.radius * -3.0f, transform.position.z);

        // ЙкНКАЁ GroundЗЙРЬОюПЁ ДъРЛ АцПь
        if(Physics.CheckBox(groundCheckPos, boxsize, Quaternion.identity, LayerMask.GetMask("Ground")))
        {
            if(!jumpCheck)
            {
                if(moveDir.y < jumpHeight)
                {
                    moveDir.y = -0.01f;
                }
                jumpCheck = false;
                jumpCount = 0;
                return true;
            }
        }
        return false;
    }

#if UNITY_EDITOR
    private void OnDrawGizmosSelected() // МБХУЧпРЛ ЖЇ
    {
    }

    private void OnDrawGizmos() // ЛѓНУ
    {
        // ЙкНК
        Gizmos.color = Color.cyan;
        Gizmos.DrawCube(groundCheckPos, boxsize);

        // ИгИЎ
        Gizmos.color = Color.white;
        Gizmos.DrawSphere(cameraRoot.transform.position, 0.25f);

        // ЛчАХИЎ
        Gizmos.color = Color.red;
        Vector2 from = cameraRoot.position;
        Vector2 to = cameraRoot.position + cameraRoot.forward * 2.0f;
        Gizmos.DrawLine(from, to);
    }
#endif
}
